#!/usr/bin/bash
#
# This script is run after the installation of Weather Station.
# We to to stop the systemd service if it is running or enabled
#

qw_service="quietwind.weather.service"
qw_install_prefix="/usr/local/qw"
qw_systemd_service_subdir="systemd/system"
qw_service_path="$qw_systemd_service_subdir/$qw_service"

#
# Check for the existence of the service file.
#
if [ ! -e /etc/$qw_service_path ]; then
  # If there isn't a link ceate it
  ln -s $qw_install_prefix/etc/$qw_service_path /etc/$qw_service_path
fi

# Check and make sure it is a link and points to the correct file
if [ ! -L /etc/$qw_service_path ] || \
   [ `realpath /etc/$qw_service_path` != "$qw_install_prefix/etc/$qw_service_path" ]; then
   echo "Improper /etc/$qw_systemd_service_subdir/$qw_service file"
  exit 1
fi

#
# Check if it is already running. If not start it
#
systemctl -q is-active $qw_service
if [ $? -ne 0 ]; then
  systemctl -q start $qw_service
fi

#
# Check if it is enabled. If not enable it
#
systemctl is-enabled $qw_service
if [ $? -ne 0 ]; then
  systemctl -q enable $qw_service
fi

exit 0
